server {
    listen 80;
    server_name localhost;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/nginx/ssl/localhost+1.pem;
    ssl_certificate_key /etc/nginx/ssl/localhost+1-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        try_files $uri $uri/ /index.html;
        autoindex off;
    }

      location /api/ {
    proxy_pass http://api:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # ✅ ESTO ES LO QUE FALTA — sin esto el 403 siempre ocurre
    proxy_set_header Authorization $http_authorization;
    proxy_pass_header Authorization;

    # ✅ Para que no falle con archivos grandes
    client_max_body_size 10M;

    
}
location /uploads/ {
  proxy_pass http://api:8080/uploads/;
  proxy_set_header Authorization $http_authorization;  # ✅ también aquí
  
}
}